TMS/Models/Salary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TMS.Models
{
    public class Salary
    {
        public int Id { get; set; }

        [Required]
        public double BasicSalary { get; set; }

        [Required]
        public double Bonus { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Required]
        public int InstructorId { get; set; }

        public Instructor Instructor { get; set; }
    }
}

TMS/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMS.Data;
using TMS.Models;

namespace TMS.Controllers
{
    public class SalariesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SalariesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Salaries
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Index(int?Iid)
        {
            var applicationDbContext = await _context.Salary.OrderBy(i => i.InstructorId).Include(s => s.Instructor).ToListAsync();
            bool onoff = false;
            if (Iid != null)
            {
                applicationDbContext = applicationDbContext.OrderBy(i => i.InstructorId).Where(t => t.InstructorId == Iid).ToList();
                onoff = true;
            }
            ViewBag.status = onoff;
            ViewBag.stext = Iid;
            return View(applicationDbContext);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorSalaryIndex(int? id)
        {
            var Iid = HttpContext.Session.GetInt32("InstructorId");
            var ISI = _context.Salary.OrderBy(i => i.InstructorId).Where(s => s.InstructorId == Iid || s.InstructorId == id).Include(s => s.Instructor);
            return View(await ISI.ToListAsync());
        }

        // GET: Salaries/Details/5
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary
                .Include(s => s.Instructor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorSalaryDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary
                .Include(s => s.Instructor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // GET: Salaries/Create
        [Authorize(Roles = "Coordinator")]
        public IActionResult Create()
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name");
            return View();
        }

        // POST: Salaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Coordinator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BasicSalary,Bonus,Date,InstructorId")] Salary salary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(salary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", salary.InstructorId);
            return View(salary);
        }

        // GET: Salaries/Edit/5
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary.SingleOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", salary.InstructorId);
            return View(salary);
        }

        // POST: Salaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Coordinator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BasicSalary,Bonus,Date,InstructorId")] Salary salary)
        {
            if (id != salary.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryExists(salary.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", salary.InstructorId);
            return View(salary);
        }

        // GET: Salaries/Delete/5
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salary
                .Include(s => s.Instructor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // POST: Salaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Coordinator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salary = await _context.Salary.SingleOrDefaultAsync(m => m.Id == id);
            _context.Salary.Remove(salary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Coordinator")]
        public IActionResult CRSearch(int? Tid)
        {
            if (Tid != null)
            {
                var searchdata = from s in _context.Salary.Include(t => t.Instructor)
                                 where s.InstructorId == Tid
                                 select s;
                var tname = from t in _context.Instructor
                            where t.Id == Tid
                            select t.Name;
                ViewBag.tn = tname.FirstOrDefault().ToString();
                ViewBag.ti = Tid;
                var sd = searchdata.ToList();
                return View("CReport", sd);
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainee, "Id", "Id");
            return View();
        }

        [Authorize(Roles = "Coordinator")]
        public IActionResult CReport()
        {
            return View();
        }

        private bool SalaryExists(int id)
        {
            return _context.Salary.Any(e => e.Id == id);
        }
    }
}

TMS/Views/Salaries/CRSearch.cshtml
@{
    ViewData["Title"] = "CRSearch";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h3 class="text-info">Search For Salary Report</h3>

<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <br />
        <br />
        <br />
        <br />
        <br />
        <form asp-action="CRSearch" class="form-inline" method="post">
            <input type="number" class="form-control" name="Tid" value="" placeholder="Search by Instructor Id" />
            <input type="submit" class="btn btn-success" value="Search" />
        </form>
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>

TMS/Views/Salaries/CReport.cshtml
@model IEnumerable<TMS.Models.Salary>

@{
    ViewData["Title"] = "CReport";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
    int i = 1;
}

<div id="print">
    <h2>Salary Report</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>Instructor name:</dt>
        <dd>@ViewBag.tn</dd>
        <dt>Instructor ID:</dt>
        <dd>@ViewBag.ti</dd>
    </dl>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    SL No.
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    Instructor Name
                </th>
                <th>
                    Instructor ID
                </th>
                <th>
                    Basic Salary
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Bonus)
                </th>
                <th>
                    Total Salary
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasicSalary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bonus)
                </td>
                <td>
                    @(Convert.ToInt32(item.BasicSalary) + (item.Bonus))
                </td>
            </tr>
                i++;
            }
        </tbody>
    </table>
</div>

<button id="pbtn" class="btn btn-success" onclick="printdiv('print');">Print</button>

<script language="javascript">
    function printdiv(printpage) {
        var newstr = document.all.item(printpage).innerHTML;
        var oldstr = document.body.innerHTML;
        document.body.innerHTML = newstr;
        window.print();
        document.body.innerHTML = oldstr;
        return false;
    }
</script>

TMS/Views/Salaries/Create.cshtml
@model TMS.Models.Salary

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h2>Create</h2>

<h4>Salary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstructorId" class="control-label">Instructor Name</label>
                <select asp-for="InstructorId" class="form-control" asp-items="ViewBag.InstructorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasicSalary" class="control-label"> Basic Salary</label>
                <input asp-for="BasicSalary" class="form-control" />
                <span asp-validation-for="BasicSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bonus" class="control-label"></label>
                <input asp-for="Bonus" class="form-control" />
                <span asp-validation-for="Bonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS/Views/Salaries/Delete.cshtml
@model TMS.Models.Salary

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BasicSalary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BasicSalary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Instructor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TMS/Views/Salaries/Details.cshtml
@model TMS.Models.Salary

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Salary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Instructor name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Name)
        </dd>
        <dt>
            Instructor ID:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Id)
        </dd>
        <dt>
           Salary Date:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
           Basic Salary:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BasicSalary)
        </dd>
        <dt>
           Bonus:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt>
            Total Salary:
        </dt>
        <dd>
            @(Convert.ToInt32(Model.BasicSalary) + (Model.Bonus))
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> 
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

TMS/Views/Salaries/Edit.cshtml
@model TMS.Models.Salary

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h2>Edit</h2>

<h4>Salary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InstructorId" class="control-label">Instructor Name</label>
                <select asp-for="InstructorId" class="form-control" asp-items="ViewBag.InstructorId"></select>
                <span asp-validation-for="InstructorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasicSalary" class="control-label">Basic Salary</label>
                <input asp-for="BasicSalary" class="form-control" />
                <span asp-validation-for="BasicSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bonus" class="control-label"></label>
                <input asp-for="Bonus" class="form-control" />
                <span asp-validation-for="Bonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS/Views/Salaries/Index.cshtml
@model IEnumerable<TMS.Models.Salary>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
    int i = 1;
}

<h2>Salary Index</h2>

<div class="row">
    <div class="col-md-10">
        <form class="form-inline" asp-controller="Salaries" asp-action="Index" method="post">
            <a asp-action="Create" class="btn btn-success">Create New</a>
            <input type="number" name="Iid" class="form-control" value="@ViewBag.stext" placeholder="Search By Trainee ID..." />
            <input type="submit" class="form-control btn btn-primary" value="Search" />
            @*@if (ViewBag.status)
        {
            <a asp-action="Index" class="btn btn-success">Back To List</a>
        }*@
        </form>
        <br />
        <a asp-action="Index" class="btn btn-success">Back To List</a>
    </div>
</div>
<br />

@*<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>*@
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                SL No.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Instructor Name
            </th>
            <th>Instructor ID</th>
            <th>
                Basic Salary
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bonus)
            </th>
            <th>
                Total Salary
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasicSalary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bonus)
                </td>
                <td>
                    @(Convert.ToInt32(item.BasicSalary) + (item.Bonus))
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                    @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>

TMS/Views/Salaries/InstructorSalaryDetails.cshtml
@model TMS.Models.Salary

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Salary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Instructor name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Name)
        </dd>
        <dt>
            Instructor ID:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Id)
        </dd>
        <dt>
            Salary Date:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            Basic Salary:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BasicSalary)
        </dd>
        <dt>
            Bonus:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt>
            Total Salary:
        </dt>
        <dd>
            @(Convert.ToInt32(Model.BasicSalary) + (Model.Bonus))
        </dd>

    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>*@
    <a asp-action="InstructorSalaryIndex" class="btn btn-primary">Back to List</a>
</div>

TMS/Views/Salaries/InstructorSalaryIndex.cshtml
@model IEnumerable<TMS.Models.Salary>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
    int i = 1;
}

<h2>Salary Index</h2>

@*<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>*@
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                SL No.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Instructor Name
            </th>
            <th>Instructor ID</th>
            <th>
                Basic Salary
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bonus)
            </th>
            <th>
                Total Salary
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasicSalary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bonus)
                </td>
                <td>
                    @(Convert.ToInt32(item.BasicSalary) + (item.Bonus))
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>*@
                    <a asp-action="InstructorSalaryDetails" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                    @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>