TMS/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMS.Data;
using TMS.Models;

namespace TMS.Controllers
{
    [Authorize(Roles = "Coordinator")]
    public class BatchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BatchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Batches
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Batch.OrderBy(b => b.Id).Include(b => b.Course).Include(b => b.Instructor);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Batches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var batch = await _context.Batch
                .Include(b => b.Course)
                .Include(b => b.Instructor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (batch == null)
            {
                return NotFound();
            }

            return View(batch);
        }

        // GET: Batches/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Set<Course>(), "Id", "Name");
            ViewData["InstructorId"] = new SelectList(_context.Set<Instructor>(), "Id", "Name");
            return View();
        }

        // POST: Batches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,CourseId,InstructorId")] Batch batch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(batch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Set<Course>(), "Id", "Name", batch.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Set<Instructor>(), "Id", "Name", batch.InstructorId);
            return View(batch);
        }

        // GET: Batches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var batch = await _context.Batch.SingleOrDefaultAsync(m => m.Id == id);
            if (batch == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Set<Course>(), "Id", "Name", batch.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Set<Instructor>(), "Id", "Name", batch.InstructorId);
            return View(batch);
        }

        // POST: Batches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,CourseId,InstructorId")] Batch batch)
        {
            if (id != batch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(batch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BatchExists(batch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Set<Course>(), "Id", "Name", batch.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Set<Instructor>(), "Id", "Name", batch.InstructorId);
            return View(batch);
        }

        // GET: Batches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var batch = await _context.Batch
                .Include(b => b.Course)
                .Include(b => b.Instructor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (batch == null)
            {
                return NotFound();
            }

            return View(batch);
        }

        // POST: Batches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var batch = await _context.Batch.SingleOrDefaultAsync(m => m.Id == id);
            _context.Batch.Remove(batch);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BatchExists(int id)
        {
            return _context.Batch.Any(e => e.Id == id);
        }
    }
}

TMS/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMS.Data;
using TMS.Models;

namespace TMS.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tasks
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Index(int?tid)
        {
            var applicationDbContext =await _context.Tasks.OrderBy(t => t.TraineeId).Include(t => t.Batch).Include(t => t.Course).Include(t => t.Instructor).Include(t => t.Trainee).OrderBy(t =>t.TraineeId).ToListAsync();
            int onoff = 0;
            if(tid != null)
            {
                applicationDbContext = applicationDbContext.OrderBy(t => t.TraineeId).Where(t => t.TraineeId == tid).ToList();
                onoff = 1;
            }
            ViewBag.status = onoff;
            ViewBag.stext = tid;
            return View(applicationDbContext);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorTaskIndex(int? id)
        {
            //var Iid = Convert.ToInt32(TempData["Instructorid"]);
            var Iid = HttpContext.Session.GetInt32("InstructorId");
            var ITI = _context.Tasks.OrderBy(t => t.TraineeId).Where(i => i.InstructorId == Iid || i.InstructorId == id).Include(t => t.Batch).Include(t => t.Course).Include(t => t.Instructor).Include(t => t.Trainee);
            return View(await ITI.ToListAsync());
        }

        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> TraineeTaskIndex(int? id)
        {
            var Tid = HttpContext.Session.GetInt32("TraineeId");
            var TTI = _context.Tasks.OrderBy(t => t.TraineeId).Where(t => t.TraineeId == Tid || t.TraineeId == id).Include(t => t.Batch).Include(t => t.Course).Include(t => t.Instructor).Include(t => t.Trainee);
            return View(await TTI.ToListAsync());
        }

        [Authorize(Roles = "Coordinator")]
        public IActionResult Search(int? cid, int? bid)
        {
            if (cid != null && bid != null)
            {
                var searchdata = _context.Tasks.OrderBy(t => t.TraineeId).Where(c => c.CourseId == cid && c.BatchId == bid).Include(t => t.Batch).Include(t => t.Course).Include(t => t.Instructor).Include(t => t.Trainee).ToList();
                return View("Index", searchdata);
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id");
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name");
            return View();
        }

        // GET: Tasks/Details/5
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .Include(t => t.Batch)
                .Include(t => t.Course)
                .Include(t => t.Instructor)
                .Include(t => t.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }

        // GET: Tasks/Details for Instructor/5
        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorTaskDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .Include(t => t.Batch)
                .Include(t => t.Course)
                .Include(t => t.Instructor)
                .Include(t => t.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }
            
            return View(tasks);
        }

        // GET: Tasks/Details for Trainee/5
        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> TraineeTaskDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .Include(t => t.Batch)
                .Include(t => t.Course)
                .Include(t => t.Instructor)
                .Include(t => t.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }

        // GET: Tasks/Create\
        [Authorize(Roles = "Instructor")]
        public IActionResult Create()
        {
            //ViewData["ReturnUrl"] = returnUrl;
            ViewBag.msg = "";
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id");
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name");
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name");
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id");
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Instructor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Number,Description,AssignDate,SubmissionDate,CourseId,BatchId,TraineeId,InstructorId")] Tasks tasks)
        {
            //ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                _context.Add(tasks);
                await _context.SaveChangesAsync();
                ViewBag.msg = "The task has been successfully assigned!";
                ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", tasks.BatchId);
                ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", tasks.CourseId);
                ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", tasks.InstructorId);
                ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", tasks.TraineeId);
                //return RedirectToAction(nameof(Index));
                //return Content("Task has been successfully assigned!");
                //return RedirectToLocal(returnUrl);
                return View("Create");
            }
            
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", tasks.BatchId);
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", tasks.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", tasks.InstructorId);
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", tasks.TraineeId);
            return View(tasks);
        }

        // GET: Tasks/Edit/5
        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks.SingleOrDefaultAsync(m => m.Id == id);
            if (tasks == null)
            {
                return NotFound();
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", tasks.BatchId);
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", tasks.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", tasks.InstructorId);
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", tasks.TraineeId);
            return View(tasks);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Instructor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Number,Description,AssignDate,SubmissionDate,CourseId,BatchId,TraineeId,InstructorId")] Tasks tasks)
        {
            if (id != tasks.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tasks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasksExists(tasks.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Status));
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", tasks.BatchId);
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", tasks.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", tasks.InstructorId);
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", tasks.TraineeId);
            return View(tasks);
        }

        [Authorize(Roles = "Instructor")]
        public IActionResult Status()
        {

TMS/Views/Shared/_CoordinatorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/admin.css" />
        <link href="https://fonts.googleapis.com/css?family=Atomic+Age" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Coordinators" asp-action="LandingPage" class="navbar-brand" style="text-shadow: 2px 2px 2px white; text-align:center; font-family:'Harlow Solid',itallic">Training Management System</a>
                </div>
                <div class="navbar-collapse collapse">
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a asp-area="" asp-controller="Trainees" asp-action="LandingPage" class="navbar-brand" style="text-shadow: 2px 2px 3px rgba(106, 15, 148, 0.80); text-align:center;  font-family:'Harlow Solid',itallic; font-size:24px;">Training Management System</a>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>

        <div class="sidenav">
            <a asp-area="" asp-controller="Coordinators" asp-action="LandingPage"><i class="glyphicon glyphicon-home"></i> Home</a>

            <button class="dropdown-btn"><i class="glyphicon glyphicon-plus-sign"></i> Add<i class="fa fa-caret-down"></i></button>
            <div class="dropdown-container">
                <a asp-area="" asp-controller="Coordinators" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Add Coordinator</a>
                <a asp-area="" asp-controller="Courses" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Add Course</a>
                <a asp-area="" asp-controller="Instructors" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Add Instructor</a>
                <a asp-area="" asp-controller="Batches" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Add Batch</a>
                <a asp-area="" asp-controller="Trainees" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Add Trainee</a>
            </div>

            <button class="dropdown-btn"><i class="glyphicon glyphicon-folder-open"></i>  View<i class="fa fa-caret-down"></i></button>
            <div class="dropdown-container">
                <a asp-area="" asp-controller="Coordinators" asp-action="Index"><i class="glyphicon glyphicon-list"></i> Coordinator info</a>
                <a asp-area="" asp-controller="Courses" asp-action="Index"><i class="glyphicon glyphicon-list"></i> Course info</a>
                <a asp-area="" asp-controller="Batches" asp-action="Index"><i class="glyphicon glyphicon-list"></i> Batch info</a>
                <a asp-area="" asp-controller="Instructors" asp-action="Index"><i class="glyphicon glyphicon-list"></i> Instructor info</a>
                <a asp-area="" asp-controller="Trainees" asp-action="Search"><i class="glyphicon glyphicon-list"></i> Trainee info</a>
                <a asp-area="" asp-controller="Tasks" asp-action="Search"><i class="glyphicon glyphicon-list"></i> Assigned Tasks</a>
                <a asp-area="" asp-controller="Progresses" asp-action="Search"><i class="glyphicon glyphicon-list"></i> Task Progress</a>
                <a asp-area="" asp-controller="Performances" asp-action="Search"><i class="glyphicon glyphicon-list"></i> Task Performances</a>
            </div>

            <button class="dropdown-btn"><i class="glyphicon glyphicon-user"></i> LogIn Management<i class="fa fa-caret-down"></i></button>
            <div class="dropdown-container">
                <a asp-area="" asp-controller="Account" asp-action="Register"><i class="glyphicon glyphicon-user"></i> Register User</a>
                <a asp-area="" asp-controller="Account" asp-action="RegisterIndex"><i class="glyphicon glyphicon-list"></i> Show User Info</a>
                <a asp-area="" asp-controller="Account" asp-action="CreateRole"><i class="glyphicon glyphicon-plus"></i> Create Role</a>
                <a asp-area="" asp-controller="Account" asp-action="AssignRole"><i class="glyphicon glyphicon-plus-sign"></i> Assign Role</a>
            </div>

            <button class="dropdown-btn"><i class="glyphicon glyphicon-book"></i> Salary<i class="fa fa-caret-down"></i></button>
            <div class="dropdown-container">
                <a asp-area="" asp-controller="Salaries" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Generate Salary</a>
                <a asp-area="" asp-controller="Salaries" asp-action="Index"><i class="glyphicon glyphicon-list"></i> Show Salary Info</a>
            </div>

            <button class="dropdown-btn"><i class="glyphicon glyphicon-floppy-disk"></i> Report<i class="fa fa-caret-down"></i></button>
            <div class="dropdown-container">
                <a asp-area="" asp-controller="Tasks" asp-action="CRSearch"><i class="glyphicon glyphicon-floppy-disk"></i> Task Report</a>
                <a asp-area="" asp-controller="Progresses" asp-action="CRSearch"><i class="glyphicon glyphicon-floppy-disk"></i> Progress Report</a>
                <a asp-area="" asp-controller="Performances" asp-action="CRSearch"><i class="glyphicon glyphicon-floppy-disk"></i> Performance Report</a>
                <a asp-area="" asp-controller="Salaries" asp-action="CRSearch"><i class="glyphicon glyphicon-floppy-disk"></i> Salary Report</a>
            </div>

            <footer style="text-align:center;margin-top:30%; color:white">
                <h5>&copy; 2019 - TMS</h5>
            </footer>
        </div>

        <partial name="_CookieConsentPartial" />

        <div class="body-content">
            @RenderBody()
        </div>
    </div>
    <script>
        /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>

    @*<div style="padding-left:14%; color:white;text-align:center" class="navbar-inverse navbar-fixed-bottom">
                &copy; 2019 - TMS
                @*<strong>Developed By:</strong> THE ANONYMOUS<br />
        </div>*@
    @*<footer class="navbar-inverse navbar-fixed-bottom text-center" style="color:white">
        <h4>&copy; 2019 - TMS</h4>
    </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Trainees" asp-action="LandingPage" class="navbar-brand" style="text-shadow: 2px 2px 3px rgba(106, 15, 148, 0.80); text-align:center;  font-family:'Harlow Solid',itallic; font-size:24px;">Training Management System</a>
            </div>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <footer class="navbar navbar-fixed-bottom text-center" style="color:rgb(106, 15, 148)">
            <h4>&copy; 2019 - TMS</h4>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>