TMS/Models/Performance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TMS.Models
{
    public class Performance
    {
        public int Id { get; set; }

        [Required]
        [Range(0, 100.00)]
        public double Accuracy { get; set; }

        [Required]
        public int CourseId { get; set; }

        [Required]
        public int BatchId { get; set; }

        [Required]
        public int TraineeId { get; set; }

        [Required]
        public int TaskId { get; set; }

        [Required]
        public int InstructorId { get; set; }

        [Required]
        public int ProgressId { get; set; }

        public Course Course { get; set; }
        public Batch Batch { get; set; }
        public Trainee Trainee { get; set; }
        public Tasks Task { get; set; }
        public Instructor Instructor { get; set; }
        public Progress Progress { get; set; }
    }
}

TMS/Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMS.Data;
using TMS.Models;

namespace TMS.Controllers
{
    public class PerformancesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PerformancesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Performances
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Index(int?tid)
        {
            var applicationDbContext =await _context.Performance.OrderBy(t => t.TraineeId).Include(p => p.Batch).Include(p => p.Course).Include(p => p.Instructor).Include(p => p.Progress).Include(p => p.Task).Include(p => p.Trainee).ToListAsync();
            int onoff = 0;
            if (tid != null)
            {
                applicationDbContext = applicationDbContext.OrderBy(t => t.TraineeId).Where(t => t.TraineeId == tid).ToList();
                onoff = 1;
            }
            ViewBag.status = onoff;
            ViewBag.stext = tid;
            return View(applicationDbContext);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorPerformanceIndex(int? id)
        {
            var Iid = HttpContext.Session.GetInt32("InstructorId");
            var IPI = _context.Performance.OrderBy(t => t.TraineeId).Where(p => p.InstructorId == Iid || p.InstructorId == id).Include(p => p.Batch).Include(p => p.Course).Include(p => p.Instructor).Include(p => p.Progress).Include(p => p.Task).Include(p => p.Trainee);
            return View(await IPI.ToListAsync());
        }

        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> TraineePerformanceIndex(int? id)
        {
            var Tid = HttpContext.Session.GetInt32("TraineeId");
            var TPI = _context.Performance.OrderBy(t => t.TraineeId).Where(p => p.TraineeId == Tid || p.TraineeId == id).Include(p => p.Batch).Include(p => p.Course).Include(p => p.Instructor).Include(p => p.Progress).Include(p => p.Task).Include(p => p.Trainee);
            return View(await TPI.ToListAsync());
        }

        [Authorize(Roles = "Coordinator")]
        public IActionResult Search(int? cid, int? bid)
        {
            if (cid != null && bid != null)
            {
                var searchdata = _context.Performance.OrderBy(t => t.TraineeId).Where(c => c.CourseId == cid && c.BatchId == bid).Include(p => p.Batch).Include(p => p.Course).Include(p => p.Instructor).Include(p => p.Progress).Include(p => p.Task).Include(p => p.Trainee).ToList();
                return View("Index", searchdata);
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id");
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name");
            return View();
        }

        // GET: Performances/Details/5
        [Authorize(Roles = "Coordinator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .Include(p => p.Batch)
                .Include(p => p.Course)
                .Include(p => p.Instructor)
                .Include(p => p.Progress)
                .Include(p => p.Task)
                .Include(p => p.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> InstructorPerformanceDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .Include(p => p.Batch)
                .Include(p => p.Course)
                .Include(p => p.Instructor)
                .Include(p => p.Progress)
                .Include(p => p.Task)
                .Include(p => p.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> TraineePerformanceDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .Include(p => p.Batch)
                .Include(p => p.Course)
                .Include(p => p.Instructor)
                .Include(p => p.Progress)
                .Include(p => p.Task)
                .Include(p => p.Trainee)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // GET: Performances/Create
        [Authorize(Roles = "Instructor")]
        public IActionResult Create()
        {
            ViewBag.msg = "";
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id");
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name");
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name");
            ViewData["ProgressId"] = new SelectList(_context.Set<Progress>(), "Id", "Id");
            ViewData["TaskId"] = new SelectList(_context.Set<Tasks>(), "Id", "Id");
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id");
            return View();
        }

        // POST: Performances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Instructor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Accuracy,CourseId,BatchId,TraineeId,TaskId,InstructorId,ProgressId")] Performance performance)
        {
            if (ModelState.IsValid)
            {
                _context.Add(performance);
                await _context.SaveChangesAsync();
                ViewBag.msg = "The performance has been submitted successfully!";
                ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", performance.BatchId);
                ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", performance.CourseId);
                ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", performance.InstructorId);
                ViewData["ProgressId"] = new SelectList(_context.Set<Progress>(), "Id", "Id", performance.ProgressId);
                ViewData["TaskId"] = new SelectList(_context.Set<Tasks>(), "Id", "Id", performance.TaskId);
                ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", performance.TraineeId);
                //return RedirectToAction(nameof(Index));
                return View("Create");
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", performance.BatchId);
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", performance.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", performance.InstructorId);
            ViewData["ProgressId"] = new SelectList(_context.Set<Progress>(), "Id", "Id", performance.ProgressId);
            ViewData["TaskId"] = new SelectList(_context.Set<Tasks>(), "Id", "Id", performance.TaskId);
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", performance.TraineeId);
            return View(performance);
        }

        // GET: Performances/Edit/5
        [Authorize(Roles = "Instructor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance.SingleOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }
            ViewData["BatchId"] = new SelectList(_context.Batch, "Id", "Id", performance.BatchId);
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", performance.CourseId);
            ViewData["InstructorId"] = new SelectList(_context.Instructor, "Id", "Name", performance.InstructorId);
            ViewData["ProgressId"] = new SelectList(_context.Set<Progress>(), "Id", "Id", performance.ProgressId);
            ViewData["TaskId"] = new SelectList(_context.Set<Tasks>(), "Id", "Id", performance.TaskId);
            ViewData["TraineeId"] = new SelectList(_context.Set<Trainee>(), "Id", "Id", performance.TraineeId);
            return View(performance);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Instructor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Accuracy,CourseId,BatchId,TraineeId,TaskId,InstructorId,ProgressId")] Performance performance)
        {
            if (id != performance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

TMS/Views/Performances/CRSearch.cshtml
@{
    ViewData["Title"] = "CRSearch";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h3 class="text-info">Search For Performance Report</h3>

<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <br />
        <br />
        <br />
        <br />
        <br />
        <form asp-action="CRSearch" class="form-inline" method="post">
            <input type="number" class="form-control" name="Tid" value="" placeholder="Search by Trainee Id" />
            <input type="submit" class="btn btn-success" value="Search" />
        </form>
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>

TMS/Views/Performances/CReport.cshtml
@model IEnumerable<TMS.Models.Performance>
@{
    ViewData["Title"] = "CReport";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
    int i = 1;
}

<div id="print">
    <h2>Performance Report</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>Trainee name:</dt>
        <dd>@ViewBag.tn</dd>
        <dt>Trainee ID:</dt>
        <dd>@ViewBag.ti</dd>
    </dl>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    SL No.
                </th>
                <th>
                    Trainee Name
                </th>
                <th>
                    Trainee ID
                </th>
                <th>
                    Task No.
                </th>
                <th>
                    Task Progress
                </th>
                <th>
                    Task Accuracy
                </th>
                <th>
                    Performance Score
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainee.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainee.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Task.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Progress.Completed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Accuracy)
                </td>
                <td>
                    @(Convert.ToInt32(item.Progress.Completed) + (item.Accuracy))
                </td>

                @if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 179)
                {
                    <td>Exelent</td>
                }
                else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 159 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 180)
                {
                    <td>Good</td>
                }
                else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 139 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 160)
                {
                    <td>Average</td>
                }
                else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 119 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 140)
                {
                    <td>Low</td>
                }
                else
                {
                    <td>Bad</td>
                }
            </tr>
                i++;
            }
        </tbody>
    </table>
</div>

<button id="pbtn" class="btn btn-success" onclick="printdiv('print');">Print</button>

<script language="javascript">
    function printdiv(printpage) {
        var newstr = document.all.item(printpage).innerHTML;
        var oldstr = document.body.innerHTML;
        document.body.innerHTML = newstr;
        window.print();
        document.body.innerHTML = oldstr;
        return false;
    }
</script>

TMS/Views/Performances/Create.cshtml
@model TMS.Models.Performance

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2>Create</h2>

<h4>Performance</h4>
<hr />
<div class="row">
    <h3 class="alert-info text-center">@ViewBag.msg</h3>
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Course Name</label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BatchId" class="control-label">Batch ID</label>
                <select asp-for="BatchId" class="form-control" asp-items="ViewBag.BatchId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TraineeId" class="control-label">Trainee ID</label>
                <select asp-for="TraineeId" class="form-control" asp-items="ViewBag.TraineeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TaskId" class="control-label">Task ID</label>
                <select asp-for="TaskId" class="form-control" asp-items="ViewBag.TaskId"></select>
            </div>
            <div class="form-group">
                <label asp-for="InstructorId" class="control-label">Instructor Name</label>
                <select asp-for="InstructorId" class="form-control" asp-items="ViewBag.InstructorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProgressId" class="control-label">Progress ID</label>
                <select asp-for="ProgressId" class="form-control" asp-items="ViewBag.ProgressId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Accuracy" class="control-label">Task Accuracy</label>
                <input asp-for="Accuracy" class="form-control" />
                <span asp-validation-for="Accuracy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="InstructorPerformanceIndex" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS/Views/Performances/Details.cshtml
@model TMS.Models.Performance

@{
    ViewData["Title"] = "Details";
     Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Performance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Trainee Name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Trainee.Name)
        </dd>
        <dt>
            Trainee ID:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Trainee.Id)
        </dd>
        <dt>
            Course Name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>
        <dt>
            Batch No:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Batch.Number)
        </dd>
        <dt>
            Task Name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Task.Name)
        </dd>
        <dt>
            Task No:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Task.Number)
        </dd>
        <dt>
            Instructor Name:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.Name)
        </dd>
        <dt>
            Task Progress:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Progress.Completed)
        </dd>
        <dt>
            Task Accuracy:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Accuracy)
        </dd>
        <dt>
            Performance Score:
        </dt>
        <dd>
            @(Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy))
        </dd>
        <dt>
            Performance Status:
        </dt>
        @if ((Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) > 179)
        {
            <dd>Exelent</dd>
        }
        else if ((Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) > 159 && (Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) < 180)
        {
            <dd>Good</dd>
        }
        else if ((Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) > 139 && (Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) < 160)
        {
            <dd>Average</dd>
        }
        else if ((Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) > 119 && (Convert.ToInt32(Model.Progress.Completed) + (Model.Accuracy)) < 140)
        {
            <dd>Low</dd>
        }
        else
        {
            <dd>Bad</dd>
        }
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>*@
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

TMS/Views/Performances/Edit.cshtml
@model TMS.Models.Performance

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2>Edit</h2>

<h4>Performance</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Course Name</label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatchId" class="control-label">Batch ID</label>
                <select asp-for="BatchId" class="form-control" asp-items="ViewBag.BatchId"></select>
                <span asp-validation-for="BatchId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TraineeId" class="control-label">Trainee ID</label>
                <select asp-for="TraineeId" class="form-control" asp-items="ViewBag.TraineeId"></select>
                <span asp-validation-for="TraineeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskId" class="control-label">Task ID</label>
                <select asp-for="TaskId" class="form-control" asp-items="ViewBag.TaskId"></select>
                <span asp-validation-for="TaskId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstructorId" class="control-label">Instructor Name</label>
                <select asp-for="InstructorId" class="form-control" asp-items="ViewBag.InstructorId"></select>
                <span asp-validation-for="InstructorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProgressId" class="control-label">Progress ID</label>
                <select asp-for="ProgressId" class="form-control" asp-items="ViewBag.ProgressId"></select>
                <span asp-validation-for="ProgressId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accuracy" class="control-label">Task Accuracy</label>
                <input asp-for="Accuracy" class="form-control" />
                <span asp-validation-for="Accuracy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="InstructorPerformanceIndex" class="btn btn-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS/Views/Performances/IRSearch.cshtml
@{
    ViewData["Title"] = "IRSearch";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h3 class="text-info">Search For Performance Report</h3>

<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <br />
        <br />
        <br />
        <br />
        <br />
        <form asp-action="IRSearch" class="form-inline" method="post">
            <input type="number" class="form-control" name="Tid" value="" placeholder="Search by Trainee Id" />
            <input type="submit" class="btn btn-success" value="Search" />
        </form>
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>

TMS/Views/Performances/Index.cshtml
@model IEnumerable<TMS.Models.Performance>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
    int i = 1;
}

<h3 class="alert bg-primary text-center">Performances List</h3>
<div class="row">
    <div class="col-md-3" style="float:right">
        <form class="form-inline" asp-controller="Performances" asp-action="Index" method="post">
            <input type="number" name="tid" class="form-control" value="@ViewBag.stext" placeholder="Search By Trainee ID..." />
            <input type="submit" class="form-control btn btn-success" value="Search" />
        </form>
    </div>
    <div class="col-md-4">
        @if (ViewBag.status == 1)
        {
            <a asp-action="Index" class="btn btn-primary">Back To List</a>
        }
    </div>
</div>
<br />

<table class="table table-bordered table-hover">
    <thead>
        <tr class="bg-primary">
            <th>
                #.
            </th>
            <th>
                Trainee Name
            </th>
            <th>
                Trainee ID
            </th>
            <th>
                Task No.
            </th>
            <th>
                Task Progress
            </th>
            <th>
                Task Accuracy
            </th>
            <th>
                Performance Score
            </th>
            <th>
                Status
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (i % 2 == 0)
            {
                <tr class="danger">
                    <td>@i.</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Trainee.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Trainee.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Task.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Progress.Completed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accuracy)
                    </td>
                    <td>
                        @(Convert.ToInt32(item.Progress.Completed) + (item.Accuracy))
                    </td>

                    @if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 179)
                    {
                        <td>Exelent</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 159 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 180)
                    {
                        <td>Good</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 139 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 160)
                    {
                        <td>Average</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 119 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 140)
                    {
                        <td>Low</td>
                    }
                    else
                    {
                        <td>Bad</td>
                    }

                    <td>
                        @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                        @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                    </td>
                </tr>
            }
            else
            {
                <tr class="warning">
                    <td>@i.</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Trainee.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Trainee.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Task.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Progress.Completed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accuracy)
                    </td>
                    <td>
                        @(Convert.ToInt32(item.Progress.Completed) + (item.Accuracy))
                    </td>

                    @if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 179)
                    {
                        <td>Exelent</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 159 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 180)
                    {
                        <td>Good</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 139 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 160)
                    {
                        <td>Average</td>
                    }
                    else if ((Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) > 119 && (Convert.ToInt32(item.Progress.Completed) + (item.Accuracy)) < 140)
                    {
                        <td>Low</td>
                    }
                    else
                    {
                        <td>Bad</td>
                    }

                    <td>
                        @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                        @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                    </td>
                </tr>
            }
            i++;
        }
    </tbody>
</table>

TMS/Views/Performances/Search.cshtml
@model TMS.Models.Performance
@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/_CoordinatorLayout.cshtml";
}

<h3 class="alert bg-primary text-center">Search for Task Performances</h3>
<br />
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form asp-action="Search" method="post">
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Course Name</label>
                <select asp-for="CourseId" class="form-control" name="cid" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BatchId" class="control-label">Batch Id</label>
                <select asp-for="BatchId" class="form-control" name="bid" asp-items="ViewBag.BatchId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

TMS/Views/Performances/Status.cshtml
@{
    ViewData["Title"] = "Status";
    Layout = "~/Views/Shared/_InstructorLayout.cshtml";
}

<h2 class="text-center text-success">@ViewBag.msg</h2>
<a asp-controller="Performances" asp-action="InstructorPerformanceIndex" class="btn btn-primary">Back To List</a>